### ISSUE TITLE
Some nodes have name "EMPTY-ID"

### ISSUE THREAD

**Issue by GuillaumeDesforges** [tweag/nixpkgs-graph-explorer#36]

**Comment by dorranh** [comment]
I'm wondering if this issue is a data model issue (i.e. elements loaded to the graph without a `pname` vertex property) or rather a parsing issue. I would imagine that it is more likely to be the former, in which case we need to identify:
1. is this expected behavior?
2. if not, we should have some tests for the `etl` process which check for this
3. if it is, we might want to introduce a fall-back for cases such as this (or ignore them entirely). Perhaps one solution would be to leave them as empty but still include them so that users can click on them and view their outputPath and other metadata.

**Comment by GuillaumeDesforges** [comment]
Not happening anymore in v1.0
